# Generated by Django 5.2.14 on 2026-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.CharField(max_length=100)),
                ('ename', models.CharField(max_length=100)),
                ('esal', models.FloatField()),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
    ]
