# Generated by Django 5.0.6 on 2026-04-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('auther', models.CharField(max_length=250)),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
