# Generated by Django 5.2.12 on 2026-03-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HydJons',
            new_name='HydJobs',
        ),
    ]
