# Generated by Django 6.0.4 on 2026-05-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentManager',
        ),
    ]
