# Generated by Django 5.2.12 on 2026-03-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='bob',
            new_name='dob',
        ),
    ]
