# Generated by Django 5.2.12 on 2026-03-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_bob_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
