# Generated by Django 5.2.12 on 2026-03-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eddr',
            new_name='eaddr',
        ),
    ]
