# Generated by Django 6.0.4 on 2026-04-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookTitle',
            new_name='title',
        ),
    ]
