# Generated by Django 6.0.4 on 2026-04-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_booktitle_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='relese_year',
            new_name='release_year',
        ),
    ]
